require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'will' do
  # rn_maps_path = '../node_modules/react-native-maps'
  # pod 'react-native-google-maps', :path => rn_maps_path
  # pod 'GoogleMaps'
  # pod 'Google-Maps-iOS-Utils'
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

permissions_path = "../node_modules/react-native-permissions/ios"
  # pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts.podspec"
  # pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  # pod 'Permission-Notifications', :path => "../node_modules/react-native-permissions/ios/Notifications.podspec"
  # pod 'Permission-Camera', :path => "../node_modules/react-native-permissions/ios/Camera.podspec"

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'RNFreshchatSDK', :path => '../node_modules/react-native-freshchat-sdk'

  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'RNCPicker', :path => '../node_modules/@react-native-community/picker'

  target 'willTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  # use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'will-tvOS' do
  # Pods for will-tvOS

  target 'will-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end